services:
  app:
    container_name: padel-hub-prod-app
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8001}:80"
    env_file:
      - stack.env
    volumes:
      - laravel-storage-production:/app/storage
    networks:
      - laravel-production
    depends_on:
      pgsql:
        condition: service_started

  nightwatch-agent:
    image: laravelphp/nightwatch-agent:latest
    environment:
      - NIGHTWATCH_TOKEN=${NIGHTWATCH_TOKEN}
      - NIGHTWATCH_REQUEST_SAMPLE_RATE=${NIGHTWATCH_REQUEST_SAMPLE_RATE:-0.4}
      - NIGHTWATCH_IGNORE_CACHE_EVENTS=true
    healthcheck:
      test: php nightwatch-status
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - laravel-production

  pgsql:
    container_name: padel-hub-prod-postgres
    image: postgres:18
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-production:/var/lib/postgresql
    networks:
      - laravel-production

networks:
  laravel-production:

volumes:
  postgres-data-production:
  laravel-storage-production:
