services:
  app:
    container_name: padel-hub-prod-app
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8001}:80"
    env_file:
      - stack.env
    volumes:
      - laravel-storage-production:/app/storage
    networks:
      - laravel-production
    depends_on:
      pgsql:
        condition: service_started

  pgsql:
    container_name: padel-hub-prod-postgres
    image: postgres:18
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-production:/var/lib/postgresql
    networks:
      - laravel-production

networks:
  laravel-production:

volumes:
  postgres-data-production:
  laravel-storage-production:
